var lalQilaResturant = {
    // ye lactaion k bare mn array he.
    branchesAddress:
    {
        karachi: "abcd-road",
        hyderabad: "abcd-road",
        lahore: "abcd-road",
        abuDhabi: "abcd-road",
        dubai: "abcd-road",
    },
    // ye resturant menue he
    buffetMenue: {
        // ye sunday menue hai
        sundayMenue: {
            soup: " Chicken Corn Soup",
            salads: [" Achar Carrot",
                "Apple Coleslaw",
                "Italian Pasta Salad",
                " Chatpatay Aloo",
                " Fresh Cut Vegetables",
                "  Papaya Salad",
                "Chick Peas Salad",
                " Greak Farmer Salad"],
            sauces: ["Chutney (Imli)",
                " Garlic Sauce",
                " Cheese Sauce",
                "Mint Raita",
                " Salsa Sauce",
                " Tartar Sauce",
                "Thai Sweet Chili Sauce"],
            breakfast: [" Butter",
                "  Jam",
                "Assorted Breads",
                "Croissant (Chocolate, Butter, Cheese)",
                " Chicken Sandwich",
                " Egg Boiled / Organic & Farmy",
                " Danish Pastry",
                " Egg Omelet",
                " Muffins",
                " Grilled Sausages",
                " Beef Patty",
                " Pan Cake",
                " French Toast",
                " Baked Beans",
                "  English Breakfast",
                " Cereals with Milk",
                " Peshawari Chai"],
            bbq: [" Beef Lebanese Kabab",
                " Chat Pata Tikka",
                "Till Wala Tikka",
                "Chicken Reshmi Kabab"],
            contineneta: ["French Fries",
                "Bar B Q Pizza"],
            seaFood: ["Zinger Fried Prawn ",
                " Fish Tikka"],

            Pakistani: ["Beef Nihari",
                " Lahori Murgh Cholay",
                " Mutton Kunna Paya",
                "Shahi Beef Daleem",
                " Chicken Masala Biryani",
                " Kabab Fry",
                " Chana Curry",
                "  Puri",
                "Kachori",
                "Suji Ka Halwa"],
            chinese: ["Cherry Chicken",
                "Fried Rice",
                "Peking Chowmein",
                "  MUGHLAI",
                " Chicken Alfredo Pasta"],
            bread: [" Qandhari Naan",
                "Roghani Naan",
                "Lacha Paratha",
                " Aloo Ka Paratha",
                " Punjabi Paratha"],
            Desserts: [" Khubani Ka Meetha",
                "Lab-E- Shereen",
                "Chocolate Fudge Cake",
                "Chocolate Brownie",
                " Cream Puff",
                "   Cream Caramel",
                "Malt Cake",
                "Assorted Mousse Glasses",
                "Chocolate Mousse Cake",
                "Coconut Kheer"],
            iceCream: ["Shahi Kulfi",
                "FRESH FRUITS",
                "Fresh Banana",
                "ONE BITE",
                " Macrons",
                " Biscuits"],
            hotDessert: " Gulab Jamun",
            sugarfreeDessert: [" Rice Pudding (Sugarfree)",
                "Ice Cream (Sugarfree)",
                "Shahi Kulfi (Sugarfree)"],
            hotDrink: ["Tea",
                "Green Tea"],
            juices: [" Lemon",
                "Mango",
                " Orange",
                " Peach",
                " PAN SHOP",
                "Pan"],

        },
        // ye lunc menue hai
        lunchMenue: {
            soup: " Chicken Corn Soup",
            salads: [" Achar Carrot",
                "Apple Coleslaw",
                "Italian Pasta Salad",
                " Chatpatay Aloo",
                " Fresh Cut Vegetables",
                "  Papaya Salad",
                "Chick Peas Salad",
                " Greak Farmer Salad"],
            sauces: ["Chutney (Imli)",
                " Garlic Sauce",
                " Cheese Sauce",
                "Mint Raita",
                " Salsa Sauce",
                " Tartar Sauce",
                "Thai Sweet Chili Sauce"],
            breakfast: [" Butter",
                "  Jam",
                "Assorted Breads",
                "Croissant (Chocolate, Butter, Cheese)",
                " Chicken Sandwich",
                " Egg Boiled / Organic & Farmy",
                " Danish Pastry",
                " Egg Omelet",
                " Muffins",
                " Grilled Sausages",
                " Beef Patty",
                " Pan Cake",
                " French Toast",
                " Baked Beans",
                "  English Breakfast",
                " Cereals with Milk",
                " Peshawari Chai"],
            bbq: [" Beef Lebanese Kabab",
                " Chat Pata Tikka",
                "Till Wala Tikka",
                "Chicken Reshmi Kabab"],
            contineneta: ["French Fries",
                "Bar B Q Pizza"],
            seaFood: ["Zinger Fried Prawn ",
                " Fish Tikka"],

            Pakistani: ["Beef Nihari",
                " Lahori Murgh Cholay",
                " Mutton Kunna Paya",
                "Shahi Beef Daleem",
                " Chicken Masala Biryani",
                " Kabab Fry",
                " Chana Curry",
                "  Puri",
                "Kachori",
                "Suji Ka Halwa"],
            chinese: ["Cherry Chicken",
                "Fried Rice",
                "Peking Chowmein",
                "  MUGHLAI",
                " Chicken Alfredo Pasta"],
            bread: [" Qandhari Naan",
                "Roghani Naan",
                "Lacha Paratha",
                " Aloo Ka Paratha",
                " Punjabi Paratha"],
            Desserts: [" Khubani Ka Meetha",
                "Lab-E- Shereen",
                "Chocolate Fudge Cake",
                "Chocolate Brownie",
                " Cream Puff",
                "   Cream Caramel",
                "Malt Cake",
                "Assorted Mousse Glasses",
                "Chocolate Mousse Cake",
                "Coconut Kheer"],
            iceCream: ["Shahi Kulfi",
                "FRESH FRUITS",
                "Fresh Banana",
                "ONE BITE",
                " Macrons",
                " Biscuits"],
            hotDessert: " Gulab Jamun",
            sugarfreeDessert: [" Rice Pudding (Sugarfree)",
                "Ice Cream (Sugarfree)",
                "Shahi Kulfi (Sugarfree)"],
            hotDrink: ["Tea",
                "Green Tea"],
            juices: [" Lemon",
                "Mango",
                " Orange",
                " Peach",
                " PAN SHOP",
                "Pan"],

        },
        // ye dinner menue he
        dinnerMenue: {
            soup: " Chicken Corn Soup",
            salads: [" Achar Carrot",
                "Apple Coleslaw",
                "Italian Pasta Salad",
                " Chatpatay Aloo",
                " Fresh Cut Vegetables",
                "  Papaya Salad",
                "Chick Peas Salad",
                " Greak Farmer Salad"],
            sauces: ["Chutney (Imli)",
                " Garlic Sauce",
                " Cheese Sauce",
                "Mint Raita",
                " Salsa Sauce",
                " Tartar Sauce",
                "Thai Sweet Chili Sauce"],
            breakfast: [" Butter",
                "  Jam",
                "Assorted Breads",
                "Croissant (Chocolate, Butter, Cheese)",
                " Chicken Sandwich",
                " Egg Boiled / Organic & Farmy",
                " Danish Pastry",
                " Egg Omelet",
                " Muffins",
                " Grilled Sausages",
                " Beef Patty",
                " Pan Cake",
                " French Toast",
                " Baked Beans",
                "  English Breakfast",
                " Cereals with Milk",
                " Peshawari Chai"],
            bbq: [" Beef Lebanese Kabab",
                " Chat Pata Tikka",
                "Till Wala Tikka",
                "Chicken Reshmi Kabab"],
            contineneta: ["French Fries",
                "Bar B Q Pizza"],
            seaFood: ["Zinger Fried Prawn ",
                " Fish Tikka"],

            Pakistani: ["Beef Nihari",
                " Lahori Murgh Cholay",
                " Mutton Kunna Paya",
                "Shahi Beef Daleem",
                " Chicken Masala Biryani",
                " Kabab Fry",
                " Chana Curry",
                "  Puri",
                "Kachori",
                "Suji Ka Halwa"],
            chinese: ["Cherry Chicken",
                "Fried Rice",
                "Peking Chowmein",
                "  MUGHLAI",
                " Chicken Alfredo Pasta"],
            bread: [" Qandhari Naan",
                "Roghani Naan",
                "Lacha Paratha",
                " Aloo Ka Paratha",
                " Punjabi Paratha"],
            Desserts: [" Khubani Ka Meetha",
                "Lab-E- Shereen",
                "Chocolate Fudge Cake",
                "Chocolate Brownie",
                " Cream Puff",
                "   Cream Caramel",
                "Malt Cake",
                "Assorted Mousse Glasses",
                "Chocolate Mousse Cake",
                "Coconut Kheer"],
            iceCream: ["Shahi Kulfi",
                "FRESH FRUITS",
                "Fresh Banana",
                "ONE BITE",
                " Macrons",
                " Biscuits"],
            hotDessert: " Gulab Jamun",
            sugarfreeDessert: [" Rice Pudding (Sugarfree)",
                "Ice Cream (Sugarfree)",
                "Shahi Kulfi (Sugarfree)"],
            hotDrink: ["Tea",
                "Green Tea"],
            juices: [" Lemon",
                "Mango",
                " Orange",
                " Peach",
                " PAN SHOP",
                "Pan"],

        },
        // ye party pakege hai
        partyPakageMenue: {
            soup: " Chicken Corn Soup",
            salads: [" Achar Carrot",
                "Apple Coleslaw",
                "Italian Pasta Salad",
                " Chatpatay Aloo",
                " Fresh Cut Vegetables",
                "  Papaya Salad",
                "Chick Peas Salad",
                " Greak Farmer Salad"],
            sauces: ["Chutney (Imli)",
                " Garlic Sauce",
                " Cheese Sauce",
                "Mint Raita",
                " Salsa Sauce",
                " Tartar Sauce",
                "Thai Sweet Chili Sauce"],
            breakfast: [" Butter",
                "  Jam",
                "Assorted Breads",
                "Croissant (Chocolate, Butter, Cheese)",
                " Chicken Sandwich",
                " Egg Boiled / Organic & Farmy",
                " Danish Pastry",
                " Egg Omelet",
                " Muffins",
                " Grilled Sausages",
                " Beef Patty",
                " Pan Cake",
                " French Toast",
                " Baked Beans",
                "  English Breakfast",
                " Cereals with Milk",
                " Peshawari Chai"],
            bbq: [" Beef Lebanese Kabab",
                " Chat Pata Tikka",
                "Till Wala Tikka",
                "Chicken Reshmi Kabab"],
            contineneta: ["French Fries",
                "Bar B Q Pizza"],
            seaFood: ["Zinger Fried Prawn ",
                " Fish Tikka"],

            Pakistani: ["Beef Nihari",
                " Lahori Murgh Cholay",
                " Mutton Kunna Paya",
                "Shahi Beef Daleem",
                " Chicken Masala Biryani",
                " Kabab Fry",
                " Chana Curry",
                "  Puri",
                "Kachori",
                "Suji Ka Halwa"],
            chinese: ["Cherry Chicken",
                "Fried Rice",
                "Peking Chowmein",
                "  MUGHLAI",
                " Chicken Alfredo Pasta"],
            bread: [" Qandhari Naan",
                "Roghani Naan",
                "Lacha Paratha",
                " Aloo Ka Paratha",
                " Punjabi Paratha"],
            Desserts: [" Khubani Ka Meetha",
                "Lab-E- Shereen",
                "Chocolate Fudge Cake",
                "Chocolate Brownie",
                " Cream Puff",
                "   Cream Caramel",
                "Malt Cake",
                "Assorted Mousse Glasses",
                "Chocolate Mousse Cake",
                "Coconut Kheer"],
            iceCream: ["Shahi Kulfi",
                "FRESH FRUITS",
                "Fresh Banana",
                "ONE BITE",
                " Macrons",
                " Biscuits"],
            hotDessert: " Gulab Jamun",
            sugarfreeDessert: [" Rice Pudding (Sugarfree)",
                "Ice Cream (Sugarfree)",
                "Shahi Kulfi (Sugarfree)"],
            hotDrink: ["Tea",
                "Green Tea"],
            juices: [" Lemon",
                "Mango",
                " Orange",
                " Peach",
                " PAN SHOP",
                "Pan"],

        },
        //  ye mango festival menue hai
        mangoFestivalMenue: {
            soup: " Chicken Corn Soup",
            salads: [" Achar Carrot",
                "Apple Coleslaw",
                "Italian Pasta Salad",
                " Chatpatay Aloo",
                " Fresh Cut Vegetables",
                "  Papaya Salad",
                "Chick Peas Salad",
                " Greak Farmer Salad"],
            sauces: ["Chutney (Imli)",
                " Garlic Sauce",
                " Cheese Sauce",
                "Mint Raita",
                " Salsa Sauce",
                " Tartar Sauce",
                "Thai Sweet Chili Sauce"],
            breakfast: [" Butter",
                "  Jam",
                "Assorted Breads",
                "Croissant (Chocolate, Butter, Cheese)",
                " Chicken Sandwich",
                " Egg Boiled / Organic & Farmy",
                " Danish Pastry",
                " Egg Omelet",
                " Muffins",
                " Grilled Sausages",
                " Beef Patty",
                " Pan Cake",
                " French Toast",
                " Baked Beans",
                "  English Breakfast",
                " Cereals with Milk",
                " Peshawari Chai"],
            bbq: [" Beef Lebanese Kabab",
                " Chat Pata Tikka",
                "Till Wala Tikka",
                "Chicken Reshmi Kabab"],
            contineneta: ["French Fries",
                "Bar B Q Pizza"],
            seaFood: ["Zinger Fried Prawn ",
                " Fish Tikka"],

            Pakistani: ["Beef Nihari",
                " Lahori Murgh Cholay",
                " Mutton Kunna Paya",
                "Shahi Beef Daleem",
                " Chicken Masala Biryani",
                " Kabab Fry",
                " Chana Curry",
                "  Puri",
                "Kachori",
                "Suji Ka Halwa"],
            chinese: ["Cherry Chicken",
                "Fried Rice",
                "Peking Chowmein",
                "  MUGHLAI",
                " Chicken Alfredo Pasta"],
            bread: [" Qandhari Naan",
                "Roghani Naan",
                "Lacha Paratha",
                " Aloo Ka Paratha",
                " Punjabi Paratha"],
            Desserts: [" Khubani Ka Meetha",
                "Lab-E- Shereen",
                "Chocolate Fudge Cake",
                "Chocolate Brownie",
                " Cream Puff",
                "   Cream Caramel",
                "Malt Cake",
                "Assorted Mousse Glasses",
                "Chocolate Mousse Cake",
                "Coconut Kheer"],
            iceCream: ["Shahi Kulfi",
                "FRESH FRUITS",
                "Fresh Banana",
                "ONE BITE",
                " Macrons",
                " Biscuits"],
            hotDessert: " Gulab Jamun",
            sugarfreeDessert: [" Rice Pudding (Sugarfree)",
                "Ice Cream (Sugarfree)",
                "Shahi Kulfi (Sugarfree)"],
            hotDrink: ["Tea",
                "Green Tea"],
            juices: [" Lemon",
                "Mango",
                " Orange",
                " Peach",
                " PAN SHOP",
                "Pan"],

        },
        // ye eid menue hai
        chotiEidMenue: {
            soup: " Chicken Corn Soup",
            salads: [" Achar Carrot",
                "Apple Coleslaw",
                "Italian Pasta Salad",
                " Chatpatay Aloo",
                " Fresh Cut Vegetables",
                "  Papaya Salad",
                "Chick Peas Salad",
                " Greak Farmer Salad"],
            sauces: ["Chutney (Imli)",
                " Garlic Sauce",
                " Cheese Sauce",
                "Mint Raita",
                " Salsa Sauce",
                " Tartar Sauce",
                "Thai Sweet Chili Sauce"],
            breakfast: [" Butter",
                "  Jam",
                "Assorted Breads",
                "Croissant (Chocolate, Butter, Cheese)",
                " Chicken Sandwich",
                " Egg Boiled / Organic & Farmy",
                " Danish Pastry",
                " Egg Omelet",
                " Muffins",
                " Grilled Sausages",
                " Beef Patty",
                " Pan Cake",
                " French Toast",
                " Baked Beans",
                "  English Breakfast",
                " Cereals with Milk",
                " Peshawari Chai"],
            bbq: [" Beef Lebanese Kabab",
                " Chat Pata Tikka",
                "Till Wala Tikka",
                "Chicken Reshmi Kabab"],
            contineneta: ["French Fries",
                "Bar B Q Pizza"],
            seaFood: ["Zinger Fried Prawn ",
                " Fish Tikka"],

            Pakistani: ["Beef Nihari",
                " Lahori Murgh Cholay",
                " Mutton Kunna Paya",
                "Shahi Beef Daleem",
                " Chicken Masala Biryani",
                " Kabab Fry",
                " Chana Curry",
                "  Puri",
                "Kachori",
                "Suji Ka Halwa"],
            chinese: ["Cherry Chicken",
                "Fried Rice",
                "Peking Chowmein",
                "  MUGHLAI",
                " Chicken Alfredo Pasta"],
            bread: [" Qandhari Naan",
                "Roghani Naan",
                "Lacha Paratha",
                " Aloo Ka Paratha",
                " Punjabi Paratha"],
            Desserts: [" Khubani Ka Meetha",
                "Lab-E- Shereen",
                "Chocolate Fudge Cake",
                "Chocolate Brownie",
                " Cream Puff",
                "   Cream Caramel",
                "Malt Cake",
                "Assorted Mousse Glasses",
                "Chocolate Mousse Cake",
                "Coconut Kheer"],
            iceCream: ["Shahi Kulfi",
                "FRESH FRUITS",
                "Fresh Banana",
                "ONE BITE",
                " Macrons",
                " Biscuits"],
            hotDessert: " Gulab Jamun",
            sugarfreeDessert: [" Rice Pudding (Sugarfree)",
                "Ice Cream (Sugarfree)",
                "Shahi Kulfi (Sugarfree)"],
            hotDrink: ["Tea",
                "Green Tea"],
            juices: [" Lemon",
                "Mango",
                " Orange",
                " Peach",
                " PAN SHOP",
                "Pan"],

        },
        // ye birthday menue hain
        birthDayMenue: {
            Desserts: [" Khubani Ka Meetha",
                "Lab-E- Shereen",
                "Chocolate Fudge Cake",
                "Chocolate Brownie",
                " Cream Puff",
                "   Cream Caramel",
                "Malt Cake",
                "Assorted Mousse Glasses",
                "Chocolate Mousse Cake",
                "Coconut Kheer"],
            iceCream: ["Shahi Kulfi",
                "FRESH FRUITS",
                "Fresh Banana",
                "ONE BITE",
                " Macrons",
                " Biscuits"],
            hotDessert: " Gulab Jamun",
            sugarfreeDessert: [" Rice Pudding (Sugarfree)",
                "Ice Cream (Sugarfree)",
                "Shahi Kulfi (Sugarfree)"],
            hotDrink: ["Tea",
                "Green Tea"],
            juices: [" Lemon",
                "Mango",
                " Orange",
                " Peach",
                " PAN SHOP",
                "Pan"],

        },
        // ye a ka reservation he
        reservationForm: {
            DateOfEvent: "a-b-c",
            DDMMYYYY: "a-b-c",
            selectSession: "a-b-c",
            PleaseSelectSession: "a-b-c",
            numberOfPersonAdult: "a-b-c",
            PleaseEnterNumberOfPersonAdult: "a-b-c",
            numberOfPersonChild: "x - y - z",
            PleaseEnterNumberOfPersonChild: "a-b-c",
            eventType: "a-b-c"
        },

        selectEventIfAny: {
            name: "a-b-c",
            PleaseEnterYourName: "a-b-c",
            eMail: "a-b-c",
            PleaseEnterYourEmailAddress: "a-b-c",
            Phone: "a-b-c",
            PleaseEnterYourPhoneOrAnyOtherNumber: "a-b-c",
            mobileNumber: "a-b-c",
            PleaseEnterYourMobileNumber: "a-b-c",
            specialRequests: "a-b-c",
        },
        // ye b ka reservation  he
        reservationForm: {
            DateOfEvent: "x-y-z",
            DDMMYYYY: "x-y-z",
            selectSession: "x-y-z",
            PleaseSelectSession: "x-y-z",
            numberOfPersonAdult: "x-y-z",
            PleaseEnterNumberOfPersonAdult: "x-y-z",
            numberOfPersonChild: "x - y - z",
            PleaseEnterNumberOfPersonChild: "x-y-z",
            eventType: "x-y-z"
        },

        selectEventIfAny: {
            name: "l-m-n",
            PleaseEnterYourName: "l-m-n",
            eMail: "l-m-n",
            PleaseEnterYourEmailAddress: "l-m-n",
            Phone: "l-m-n",
            PleaseEnterYourPhoneOrAnyOtherNumber: "l-m-n",
            mobileNumber: "l-m-n",
            PleaseEnterYourMobileNumber: "l-m-n",
            specialRequests: "l-m-n",
        },
        // ye c ka reservation   he
        reservationForm: {
            DateOfEvent: "l-m-n",
            DDMMYYYY: "l-m-n",
            selectSession: "l-m-n",
            PleaseSelectSession: "l-m-n",
            numberOfPersonAdult: "l-m-n",
            PleaseEnterNumberOfPersonAdult: "l-m-n",
            numberOfPersonChild:" x - y - z",
            PleaseEnterNumberOfPersonChild: "l-m-n",
            eventType: "l-m-n"
        },

        selectEventIfAny: {
            name: "q-r-s",
            PleaseEnterYourName: "q-r-s",
            eMail: "q-r-s",
            PleaseEnterYourEmailAddress: "q-r-s",
            Phone: "q-r-s",
            PleaseEnterYourPhoneOrAnyOtherNumber: "q-r-s",
            mobileNumber: "q-r-s",
            PleaseEnterYourMobileNumber: "q-r-s",
            specialRequests: "q-r-s",
        },
        // ye d ki hai
        reservationForm: {
            DateOfEvent: "q-r-s",
            DDMMYYYY: "q-r-s",
            selectSession: "q-r-s",
            PleaseSelectSession: "q-r-s",
            numberOfPersonAdult: "q-r-s",
            PleaseEnterNumberOfPersonAdult: "q-r-s",
            numberOfPersonChild:" x - y - z",
            PleaseEnterNumberOfPersonChild: "q-r-s",
            eventType: "q-r-s"
        },

        selectEventIfAny: {
            name: "y-u-v",
            PleaseEnterYourName: "y-u-v",
            eMail: "y-u-v",
            PleaseEnterYourEmailAddress: "y-u-v",
            Phone: "y-u-v",
            PleaseEnterYourPhoneOrAnyOtherNumber: "y-u-v",
            mobileNumber: "y-u-v",
            PleaseEnterYourMobileNumber: "y-u-v",
            specialRequests: "y-u-v",
        },
        // ye e ki hai
        reservationForm: {
            DateOfEvent: "y-u-v",
            DDMMYYYY: "y-u-v",
            selectSession: "y-u-v",
            PleaseSelectSession: "y-u-v",
            numberOfPersonAdult: "y-u-v",
            PleaseEnterNumberOfPersonAdult: "y-u-v",
            numberOfPersonChild:" x - y - z",
            PleaseEnterNumberOfPersonChild: "y-u-v",
            eventType: "y-u-v"
        },

        selectEventIfAny: {
            name: "e-g-f",
            PleaseEnterYourName: "e-g-f",
            eMail: "e-g-f",
            PleaseEnterYourEmailAddress: "e-g-f",
            Phone: "e-g-f",
            PleaseEnterYourPhoneOrAnyOtherNumber: "e-g-f",
            mobileNumber: "e-g-f",
            PleaseEnterYourMobileNumber: "e-g-f",
            specialRequests: "e-g-f",
        },
        // ye f ki hai
        reservationForm: {
            DateOfEvent: "e-g-f",
            DDMMYYYY: "e-g-f",
            selectSession: "e-g-f",
            PleaseSelectSession: "e-g-f",
            numberOfPersonAdult: "e-g-f",
            PleaseEnterNumberOfPersonAdult: "e-g-f",
            numberOfPersonChild:" x - y - z",
            PleaseEnterNumberOfPersonChild: "e-g-f",
            eventType: "e-g-f"
        },

        selectEventIfAny: {
            name: "j-k-l",
            PleaseEnterYourName: "j-k-l",
            eMail: "j-k-l",
            PleaseEnterYourEmailAddress: "j-k-l",
            Phone: "j-k-l",
            PleaseEnterYourPhoneOrAnyOtherNumber: "j-k-l",
            mobileNumber: "j-k-l",
            PleaseEnterYourMobileNumber: "j-k-l",
            specialRequests: "j-k-l",
        },
        // ye g ki hai
        reservationForm: {
            DateOfEvent: "j-k-l",
            DDMMYYYY: "j-k-l",
            selectSession: "j-k-l",
            PleaseSelectSession: "j-k-l",
            numberOfPersonAdult: "j-k-l",
            PleaseEnterNumberOfPersonAdult: "j-k-l",
            numberOfPersonChild: "x - y - z",
            PleaseEnterNumberOfPersonChild: "j-k-l",
            eventType: "j-k-l"
        },

        selectEventIfAny: {
            name: "x-y-z",
            PleaseEnterYourName: "x-y-z",
            eMail: "x-y-z",
            PleaseEnterYourEmailAddress: "x-y-z",
            Phone: "x-y-z",
            PleaseEnterYourPhoneOrAnyOtherNumber: "x-y-z",
            mobileNumber: "x-y-z",
            PleaseEnterYourMobileNumber: "x-y-z",
            specialRequests: "x-y-z",
        },
        // f ki hai
        reservationForm: {
            DateOfEvent: "a-b-c",
            DDMMYYYY: "a-b-c",
            selectSession: "a-b-c",
            PleaseSelectSession: "a-b-c",
            numberOfPersonAdult: "a-b-c",
            PleaseEnterNumberOfPersonAdult: "a-b-c",
            numberOfPersonChild:" a - b - c",
            PleaseEnterNumberOfPersonChild: "a-b-c",
            eventType: "a-b-c"
        },

        selectEventIfAny: {
            name: "a-b-c",
            PleaseEnterYourName: "a-b-c",
            eMail: "a-b-c",
            PleaseEnterYourEmailAddress: "a-b-c",
            Phone: "a-b-c",
            PleaseEnterYourPhoneOrAnyOtherNumber: "a-b-c",
            mobileNumber: "a-b-c",
            PleaseEnterYourMobileNumber: "a-b-c",
            specialRequests: "a-b-c",
        },
        // ye h ki hai
        reservationForm: {
            DateOfEvent: "d-e-f",
            DDMMYYYY: "d-e-f",
            selectSession: "d-e-f",
            PleaseSelectSession: "d-e-f",
            numberOfPersonAdult: "d-e-f",
            PleaseEnterNumberOfPersonAdult: "d-e-f",
            numberOfPersonChild:" d - e - f",
            PleaseEnterNumberOfPersonChild: "d-e-f",
            eventType: "d-e-f"
        },

        selectEventIfAny: {
            name: "d-e-f",
            PleaseEnterYourName: "d-e-f",
            eMail: "d-e-f",
            PleaseEnterYourEmailAddress: "d-e-f",
            Phone: "d-e-f",
            PleaseEnterYourPhoneOrAnyOtherNumber: "d-e-f",
            mobileNumber: "d-e-f",
            PleaseEnterYourMobileNumber: "d-e-f",
            specialRequests: "d-e-f",
        },
        //  ye i ki hai
        reservationForm: {
            DateOfEvent: "q-l-m",
            DDMMYYYY: "q-l-m",
            selectSession: "q-l-m",
            PleaseSelectSession: "q-l-m",
            numberOfPersonAdult: "q-l-m",
            PleaseEnterNumberOfPersonAdult: "q-l-m",
            numberOfPersonChild:" q - l - m",
            PleaseEnterNumberOfPersonChild: "q-l-m",
            eventType: "q-l-m"
        },

        selectEventIfAny: {
            name: "q-l-m",
            PleaseEnterYourName: "q-l-m",
            eMail: "q-l-m",
            PleaseEnterYourEmailAddress: "q-l-m",
            Phone: "q-l-m",
            PleaseEnterYourPhoneOrAnyOtherNumber: "q-l-m",
            mobileNumber: "q-l-m",
            PleaseEnterYourMobileNumber: "q-l-m",
            specialRequests: "q-l-m",
        },
        // ye j ki hai
        reservationForm: {
            DateOfEvent: "u-v-w",
            DDMMYYYY: "u-v-w",
            selectSession: "u-v-w",
            PleaseSelectSession: "u-v-w",
            numberOfPersonAdult: "u-v-w",
            PleaseEnterNumberOfPersonAdult: "u-v-w",
            numberOfPersonChild:" u - v - w",
            PleaseEnterNumberOfPersonChild: "u-v-w",
            eventType: "u-v-w"
        },

        selectEventIfAny: {
            name: "u-v-w",
            PleaseEnterYourName: "u-v-w",
            eMail: "u-v-w",
            PleaseEnterYourEmailAddress: "u-v-w",
            Phone: "u-v-w",
            PleaseEnterYourPhoneOrAnyOtherNumber: "u-v-w",
            mobileNumber: "u-v-w",
            PleaseEnterYourMobileNumber: "u-v-w",
            specialRequests: "u-v-w",
        },
        // ye m ki hai
        reservationForm: {
            DateOfEvent: "u-f-g",
            DDMMYYYY: "u-f-g",
            selectSession: "u-f-g",
            PleaseSelectSession: "u-f-g",
            numberOfPersonAdult: "u-f-g",
            PleaseEnterNumberOfPersonAdult: "u-f-g",
            numberOfPersonChild:" u - f - g",
            PleaseEnterNumberOfPersonChild: "u-f-g",
            eventType: "u-f-g"
        },

        selectEventIfAny: {
            name: "u-f-g",
            PleaseEnterYourName: "u-f-g",
            eMail: "u-f-g",
            PleaseEnterYourEmailAddress: "u-f-g",
            Phone: "u-f-g",
            PleaseEnterYourPhoneOrAnyOtherNumber: "u-f-g",
            mobileNumber: "u-f-g",
            PleaseEnterYourMobileNumber: "u-f-g",
            specialRequests: "u-f-g",
        },
        // ye n ki hai
        reservationForm: {
            DateOfEvent: "l-m-n",
            DDMMYYYY: "l-m-n",
            selectSession: "l-m-n",
            PleaseSelectSession: "l-m-n",
            numberOfPersonAdult: "l-m-n",
            PleaseEnterNumberOfPersonAdult: "l-m-n",
            numberOfPersonChild: "l - m - n",
            PleaseEnterNumberOfPersonChild: "l-m-n",
            eventType: "l-m-n"
        },

        selectEventIfAny: {
            name: "l-m-n",
            PleaseEnterYourName: "l-m-n",
            eMail: "l-m-n",
            PleaseEnterYourEmailAddress: "l-m-n",
            Phone: "l-m-n",
            PleaseEnterYourPhoneOrAnyOtherNumber: "l-m-n",
            mobileNumber: "l-m-n",
            PleaseEnterYourMobileNumber: "l-m-n",
            specialRequests: "l-m-n",
        },
        // ye o ki hai
        reservationForm: {
            DateOfEvent: "d-e-f",
            DDMMYYYY: "d-e-f",
            selectSession: "d-e-f",
            PleaseSelectSession: "d-e-f",
            numberOfPersonAdult: "d-e-f",
            PleaseEnterNumberOfPersonAdult: "d-e-f",
            numberOfPersonChild: "d - e - f",
            PleaseEnterNumberOfPersonChild: "d-e-f",
            eventType: "d-e-f"
        },

        selectEventIfAny: {
            name: "d-e-f",
            PleaseEnterYourName: "d-e-f",
            eMail: "d-e-f",
            PleaseEnterYourEmailAddress: "d-e-f",
            Phone: "d-e-f",
            PleaseEnterYourPhoneOrAnyOtherNumber: "d-e-f",
            mobileNumber: "d-e-f",
            PleaseEnterYourMobileNumber: "d-e-f",
            specialRequests: "d-e-f",
        },
        // ye arifa ki event bookin hai
        eventBooking: {
            name: "arifa",
            emailId: "abcd@gmail.com",
            PhoneNo: "0333-2158336",
            TypeOfEvent: "birthday",
            NumberOfPeople: "30",
            Message: "ba bla bla",
        },
        // ye sofia ki event bookin hai
        eventBooking: {
            name: "sofia",
            emailId: "abcd@gmail.com",
            PhoneNo: "0333-2158336",
            TypeOfEvent: "wedding-aniversary",
            NumberOfPeople: "10",
            Message: "ba bla bla",
        },
        // ye ali ki booking
        eventBooking: {
            name: "ali",
            emailId: "abcd@gmail.com",
            PhoneNo: "0333-2158336",
            TypeOfEvent: "abc-party",
            NumberOfPeople: "300",
            Message: "ba bla bla",
        },
        // ye ahmed ki hai
        eventBooking: {
            name: "ahmed",
            emailId: "abcd@gmail.com",
            PhoneNo: "0333-2158336",
            TypeOfEvent: "birthday-party",
            NumberOfPeople: "100",
            Message: "ba bla bla",
        },
        // ye jamila ki hai
        eventBooking: {
            name: "jamila",
            emailId: "abcd@gmail.com",
            PhoneNo: "0333-2158336",
            TypeOfEvent: "bla bla party",
            NumberOfPeople: "100",
            Message: "ba bla bla",
        },
        // ye akmal ki hai

        eventBooking: {
            name: "akmal",
            emailId: "abcd@gmail.com",
            PhoneNo: "0333-2158336",
            TypeOfEvent: "farewell party",
            NumberOfPeople: "100",
            Message: "ba bla bla",
        },
       
        contacts: [
            "0333-2158336",
            "033-21583366"]
    },
    contactInfo: [
        "Tulip Al Barsha Hotel Apartments, Barsha 1",
        "Dubai. United Arab Emirates",
        "info@lalqila-mumtaz.com",
        "www.lalqila-mumtaz.com"],

}